#!/bin/bash

if [ "$#" -eq 0 ]
then
  echo "Usage: $(basename $0) [--init] host"
  exit 1
fi

READY_CHECK="/var/lib/reactor/ready_check"

if [ "$1" == "--init" ]
then
  mkdir -p "/var/lib/reactor/ready_check"
  rm -f $READY_CHECK/*
  exit 0
fi

touch $READY_CHECK/$1
complete=1
for node in `salt-run manage.present | cut -f2 -d\ `
do
  if [ ! -f "$READY_CHECK/$node" ]
  then
    complete=0
    break
  fi
done

if [ $complete -eq 1 ]
then
  # Send event
  echo "Firing event"
  salt 'admin.ceph' event.fire_master '{"data":"start deploying"}' 'stage/deploy/start'
fi


