#!/bin/bash

for i in `awk '/-public/ {print $3}' /etc/hosts`
do
  ssh $i "mv /etc/salt/minion.d/transport-raet.conf /etc/salt/minion.d/transport-raet.conf-"
  ssh $i systemctl start salt-minion
  ssh $i systemctl enable salt-minion
done

