#!/usr/bin/python

import salt.client
import salt.runner
import salt.queues.sqlite_queue
import salt.config

global __opts__
__opts__ = salt.config.client_config('/etc/salt/master')

def run():
    '''
    Install the django package
    '''
   
    queues = salt.queues.sqlite_queue.list_queues()
    runner = salt.runner.RunnerClient(opts)
    ret = runner.cmd('queue.list_length', [ 'prep_complete' ])
    return { 'example': {'cmd.run': [ { 'name': 'echo "Hello {}"'.format(ret) } ]}}

print run()
